services:
  sge:
    image: sge-app:0.0.1
    container_name: sge-app
    ports:
      - "8000:8000"
    networks:
      - sge-network
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-sge:5432/postgres 
      - EVOLUTION_API_BASE_URL=http://evolution_api:8080/
      - EVOLUTION_API_TOKEN=429683C4C977415CAAFCCE10F7D57E11
    depends_on:
      - db
    command: >
      sh -c "python3 manage.py wait_for_db && \
      python3 manage.py migrate && \ 
      python3 manage.py createuser && \
      python3 manage.py runserver 0.0.0.0:8000"
  
  db:
    container_name: db-sge
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sge-network

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  sge-network:
    driver: bridge
