# Generated by Django 5.1.4 on 2025-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='total_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
