# Generated by Django 5.1.4 on 2024-12-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saída', 'verbose_name_plural': 'Saídas'},
        ),
    ]
