# Generated by Django 5.1.4 on 2025-02-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_outflow_total_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='total_cost_price',
        ),
    ]
