# Generated by Django 5.1.4 on 2024-12-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
